config/routes.rb
Rails.application.routes.draw do
  resources :foros
  resources :profesor_alumnos
  resources :alumnos
  resources :profesors
  resources :especialidads
  root :to => 'inicio#index'
  get 'inicio/index'

  devise_for :usuarios

end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
  has_many :profesor_alumnos
  has_many :profesor, :through => :profesor_alumnos

  validates :nombreal, presence: true
  validates :appal, presence: true

end

app/models/especialidad.rb
class Especialidad < ActiveRecord::Base
has_many :profesor

validates :nombre, presence: true


end

app/models/foro.rb
class Foro < ActiveRecord::Base
  belongs_to :usuario
end

app/models/profesor.rb
class Profesor < ActiveRecord::Base
  belongs_to :especialidad
  has_many :profesor_alumnos
  has_many :alumno, :through => :profesor_alumnos

  validates :nombreprof, presence: true
  validates :approf, presence: true
  validates :correo, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :correo, format: { :with => VALID_EMAIL_REGEX , message: "El formato del correo es invalido" }
  validates :especialidad, presence: true
end

app/models/profesor_alumno.rb
class ProfesorAlumno < ActiveRecord::Base
  belongs_to :profesor
  belongs_to :alumno


  validates :profesor, presence: true
  validates :alumno, presence: true


end

app/models/usuario.rb
class Usuario < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable




end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: [:show, :edit, :update, :destroy]

  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
    @profesors =@alumno.profesor.all
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = Alumno.new(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno was successfully created.' }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1
  # PATCH/PUT /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: 'Alumno was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno.destroy
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: 'Alumno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_params
      params.require(:alumno).permit(:nombreal, :appal)
    end
end

app/controllers/foros_controller.rb
class ForosController < ApplicationController
  before_action :set_foro, only: [:show, :edit, :update, :destroy]

  # GET /foros
  # GET /foros.json
  def index
    @foros = Foro.all
  end

  # GET /foros/1
  # GET /foros/1.json
  def show
  end

  # GET /foros/new
  def new
    @foro = Foro.new
  end

  # GET /foros/1/edit
  def edit
  end

  # POST /foros
  # POST /foros.json
  def create
    @foro = Foro.new(foro_params)

    respond_to do |format|
      if @foro.save
        format.html { redirect_to @foro, notice: 'Foro was successfully created.' }
        format.json { render :show, status: :created, location: @foro }
      else
        format.html { render :new }
        format.json { render json: @foro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foros/1
  # PATCH/PUT /foros/1.json
  def update
    respond_to do |format|
      if @foro.update(foro_params)
        format.html { redirect_to @foro, notice: 'Foro was successfully updated.' }
        format.json { render :show, status: :ok, location: @foro }
      else
        format.html { render :edit }
        format.json { render json: @foro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foros/1
  # DELETE /foros/1.json
  def destroy
    @foro.destroy
    respond_to do |format|
      format.html { redirect_to foros_url, notice: 'Foro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foro
      @foro = Foro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foro_params
      params.require(:foro).permit(:titulo, :contenido, :usuario_id)
    end
end

app/controllers/profesors_controller.rb
class ProfesorsController < ApplicationController
  before_action :set_profesor, only: [:show, :edit, :update, :destroy]

  # GET /profesors
  # GET /profesors.json
  def index
    @profesors = Profesor.all
  end

  # GET /profesors/1
  # GET /profesors/1.json
  def show
    @alumnos = @profesor.alumno.all
  end

  # GET /profesors/new
  def new
    @profesor = Profesor.new
  end

  # GET /profesors/1/edit
  def edit
  end

  # POST /profesors
  # POST /profesors.json
  def create
    @profesor = Profesor.new(profesor_params)

    respond_to do |format|
      if @profesor.save
        format.html { redirect_to @profesor, notice: 'Profesor was successfully created.' }
        format.json { render :show, status: :created, location: @profesor }
      else
        format.html { render :new }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profesors/1
  # PATCH/PUT /profesors/1.json
  def update
    respond_to do |format|
      if @profesor.update(profesor_params)
        format.html { redirect_to @profesor, notice: 'Profesor was successfully updated.' }
        format.json { render :show, status: :ok, location: @profesor }
      else
        format.html { render :edit }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profesors/1
  # DELETE /profesors/1.json
  def destroy
    @profesor.destroy
    respond_to do |format|
      format.html { redirect_to profesors_url, notice: 'Profesor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profesor
      @profesor = Profesor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profesor_params
      params.require(:profesor).permit(:nombreprof, :approf, :correo, :especialidad_id)
    end
end

app/helpers/foros_helper.rb
module ForosHelper
end

app/views/alumnos/_form.html.erb
<center>
<%= form_for(@alumno) do |f| %>
  <% if @alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% @alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombreal %><br>
    <%= f.text_field :nombreal %>
  </div>
  <div class="field">
    <%= f.label :appal %><br>
    <%= f.text_field :appal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</center>

app/views/alumnos/edit.html.erb
<center><h1>Modificar datos Alumno</h1></center>

<%= render 'form' %>

<center><%= link_to 'Show', @alumno %> |
<%= link_to 'Back', alumnos_path %></center>

app/views/alumnos/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Alumnos</div>

<table>
  <thead>
    <tr>
      <table class="table">

      <th>Nombre  </th>
      <th>Apellido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnos.each do |alumno| %>
      <tr>
        <td><%= alumno.nombreal %></td>
        <td><%= alumno.appal %></td>
        <td><%= link_to 'Show', alumno %></td>
        <td><%= link_to 'Edit', edit_alumno_path(alumno) %></td>
        <td><%= link_to 'Destroy', alumno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<center><%= link_to 'Agregar Alumno', new_alumno_path %></center>
<center><%= link_to 'Atras', inicio_index_path %></center>

app/views/alumnos/new.html.erb
<center><h1>Agregar Alumno</h1></center>

<%= render 'form' %>

<center><%= link_to 'Back', alumnos_path %></center>

app/views/alumnos/show.html.erb
<div class="panel panel-default">

  <div class="panel-heading">Alumnos</div>
  <p>
    <table>
      <thead>
        <tr>
    <table class="table">
<strong>Nombre: </strong>
<%= @alumno.nombreal %>
</p>
<p>
<strong>Apellido: </strong>
<%= @alumno.appal %></strong>
</p>
</tr>
</thead>
</table>
</div>
<div class="panel panel-default">
<div class="panel-heading">Profesores del Alumno</div>
<p>
  <table>
    <thead>
      <tr><% @profesors.each do |profesor| %>
  <strong>Nombre:</strong>
  <%= profesor.nombreprof %>
  <strong>Apellido:</strong>
  <%= profesor.approf %>
  <strong>Especialidad:</strong>
  <%= profesor.especialidad.nombre %>
  <br>
</tr>
</thead>
<br>
</table>
<% end %>
</div>
<br>

<%= link_to 'Editar', edit_alumno_path(@alumno) %> |
<%= link_to 'Atras', inicio_index_path %>

app/views/especialidads/_form.html.erb
<center>
<%= form_for(@especialidad) do |f| %>
  <% if @especialidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@especialidad.errors.count, "error") %> prohibited this especialidad from being saved:</h2>

      <ul>
      <% @especialidad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</center>

app/views/especialidads/edit.html.erb
<center><h1>Modificar Especialidad</h1></center>

<%= render 'form' %>

<center><%= link_to 'Show', @especialidad %> |
<%= link_to 'Back', especialidads_path %></center>

app/views/especialidads/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Especialidades</div>

<table>
  <thead>
    <tr>
      <table class="table">
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @especialidads.each do |especialidad| %>
      <tr>
        <td><%= especialidad.nombre %></td>
        <td><%= link_to 'Show', especialidad %></td>
        <td><%= link_to 'Edit', edit_especialidad_path(especialidad) %></td>
        <td><%= link_to 'Destroy', especialidad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<center>
<%= link_to 'Agregar especialidad', new_especialidad_path %>
</center>

app/views/especialidads/new.html.erb
<center><h1>Ingresar Especialidades</h1></center>

<%= render 'form' %>

<center><%= link_to 'Back', especialidads_path %></center>

app/views/especialidads/show.html.erb
<div class="panel panel-default">

  <div class="panel-heading">ESPECIALIDAD</div>

<p>
  <strong>Nombre:</strong>
  <%= @especialidad.nombre %>
</p>

</div>
<%= link_to 'Editar', edit_especialidad_path(@especialidad) %> |
<%= link_to 'Atras', especialidads_path %>

app/views/foros/_form.html.erb
<%= form_for(@foro) do |f| %>
  <% if @foro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foro.errors.count, "error") %> prohibited this foro from being saved:</h2>

      <ul>
      <% @foro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </div>
  <%= f.hidden_field :usuario_id, :value => current_usuario.id   %>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/foros/edit.html.erb
<h1>Editing Foro</h1>

<%= render 'form' %>

<%= link_to 'Show', @foro %> |
<%= link_to 'Back', foros_path %>

app/views/foros/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Temas</div>

<table>
  <thead>
    <tr>
      <table class="table">
      <th>Titulo</th>
      <th>Contenido</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foros.each do |foro| %>
      <tr>
        <td><%= foro.titulo %></td>
        <td><%= foro.contenido %></td>
        <td><%= foro.usuario.email %></td>
        <td><%= link_to 'Show', foro %></td>
        <% if current_usuario.email == foro.usuario.email %>
        <td><%= link_to 'Edit', edit_foro_path(foro) %></td>
        <td><%= link_to 'Destroy', foro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>

<br>
<center>
<%= link_to 'Nuevo Tema', new_foro_path %>
</center>

app/views/foros/new.html.erb
<h1>New Foro</h1>

<%= render 'form' %>

<%= link_to 'Back', foros_path %>

app/views/foros/show.html.erb
<div class="panel panel-default">

  <div class="panel-heading">Foros</div>
<p>
  <table>
    <thead>
      <tr>
  <table class="table">
  <strong>Titulo:</strong>
  <%= @foro.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @foro.contenido %>
</p>

<p>
  <strong>By:</strong>
  <%= @foro.usuario.email%>
</p>
</thead>
</table>
</div>
<% if current_usuario.email == @foro.usuario.email %>
<%= link_to 'Edit', edit_foro_path(@foro) %> |
<%= link_to 'Back', foros_path %>
<% end %>

app/views/inicio/index.html.erb
<h1>Bienvenidos al Instituto</h1>
<p>Crea un Usuario en la esquina superior derecha para ver el contenido</p>

<br>
<br>

 <h4>Dentro de nuestra pagina podras crear profesores, alumnos e ingresar especialidades<br>
  para cada profesor, por esto mismo, ingresa a tu cuenta para poder conocer todo lo que<br>
  puedes hacer en nuestra pagina, o tambien crear tu propio usuario y accede a nuestra pagina.<br>
  <br>

  Contamos ademas con un Foro para que puedas compartir tus opiniones, temas de interes, noticias, etc.

<br>
 <h1>Te esperamos!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>INSTITUTO</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/alert' %>'


<%= yield %>

</body>
</html>

app/views/profesor_alumnos/_form.html.erb
<center>
<%= form_for(@profesor_alumno) do |f| %>
  <% if @profesor_alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profesor_alumno.errors.count, "error") %> prohibited this profesor_alumno from being saved:</h2>

      <ul>
      <% @profesor_alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profesor_id %><br>
    <%= f.select( "profesor_id",Profesor.all.collect{|l| [ l.nombreprof, l.id ] }, {include_blank: 'Seleccione Profesor'}) %>
  </div>
  <div class="field">
    <%= f.label :alumno_id %><br>
    <%= f.select( "alumno_id",Alumno.all.collect{|l| [ l.nombreal, l.id ] }, {include_blank: 'Seleccione Alumno'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</center>

app/views/profesor_alumnos/index.html.erb
<div class="panel panel-default">

  <div class="panel-heading">PROFESOR-ALUMNNO</div>

<table>
  <thead>
    <tr>
      <table class="table">
      <th>Profesor</th>
      <th>Alumno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profesor_alumnos.each do |profesor_alumno| %>
      <tr>
        <td><%= profesor_alumno.profesor %></td>
        <td><%= profesor_alumno.alumno %></td>
        <td><%= link_to 'Show', profesor_alumno %></td>
        <td><%= link_to 'Edit', edit_profesor_alumno_path(profesor_alumno) %></td>
        <td><%= link_to 'Destroy', profesor_alumno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<center><%= link_to 'Nueva relacion profesor - alumno', new_profesor_alumno_path %></center>

app/views/profesor_alumnos/new.html.erb
<center><h1>Relacionar Profesor Alumno</h1></center>

<%= render 'form' %>

<center><%= link_to 'Atras', profesor_alumnos_path %></center>

app/views/profesor_alumnos/show.html.erb
  <strong>Profesor:</strong>
  <%= @profesor_alumno.profesor %>
</p>

<p>
  <strong>Alumno:</strong>
  <%= @profesor_alumno.alumno %>
</p>

<%= link_to 'Edit', edit_profesor_alumno_path(@profesor_alumno) %> |
<%= link_to 'Back', profesor_alumnos_path %>

app/views/profesors/_form.html.erb
<center>
<%= form_for(@profesor) do |f| %>
  <% if @profesor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profesor.errors.count, "error") %> prohibited this profesor from being saved:</h2>

      <ul>
      <% @profesor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombreprof %><br>
    <%= f.text_field :nombreprof %>
  </div>
  <div class="field">
    <%= f.label :approf %><br>
    <%= f.text_field :approf %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="field">
    <%= f.label :especialidad_id %><br>
    <%= f.select("especialidad_id", Especialidad.all.collect{|l| [ l.nombre, l.id ] }, {include_blank: 'Seleccione Especialidad'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</center>

app/views/profesors/edit.html.erb
<center><h1>Modificar Profesor</h1></center>

<%= render 'form' %>

<center><%= link_to 'Ver', @profesor %>  </center>
<center><%= link_to 'Atras', profesors_path %> </center>

app/views/profesors/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Profesores</div>

<table>
  <thead>
    <tr>
      <table class="table">

      <th>Nombre</th>
      <th>Apellido</th>
      <th>Correo</th>
      <th>Especialidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profesors.each do |profesor| %>
      <tr>
        <td><%= profesor.nombreprof %></td>
        <td><%= profesor.approf %></td>
        <td><%= profesor.correo %></td>
        <td><%= profesor.especialidad.nombre %></td>
        <td><%= link_to 'Show', profesor %></td>
        <td><%= link_to 'Edit', edit_profesor_path(profesor) %></td>
        <td><%= link_to 'Destroy', profesor, method: :delete, data: { confirm: 'Seguro que quieres eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<center><%= link_to 'Agregar Profesor', new_profesor_path %></center>
<center><%= link_to 'Atras', inicio_index_path %></center>

app/views/profesors/new.html.erb
<H1 align="center"> Agregar Profesor </H1>

<%= render 'form' %>

<center><%= link_to 'Atras', inicio_index_path %></center>

app/views/profesors/show.html.erb
<div class="panel panel-default">

  <div class="panel-heading">Profesor</div>
  <p>
   <table>
     <thead>
       <tr>
  <table class="table">
  <strong>Nombre:</strong>
  <%= @profesor.nombreprof %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @profesor.approf %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @profesor.correo %>
</p>

<p>
  <strong>Especialidad:</strong>
  <%= @profesor.especialidad.nombre %>
</p>
</tr>
</thead>
<br>
</table>
</div>
<div class="panel panel-default">
  <div class="panel-heading">Alumnos</div>

  <p>
  <%@alumnos.each do |alumno| %>
  <strong>Nombre:<STRONG>
  <%=alumno.nombreal %>
  </p>
  <p>
  <strong>Apellido:<STRONG>
  <%=alumno.appal %>
  </p>
<% end %>

<p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">INSTITUTO </a>
    </div>
<!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <% if usuario_signed_in? %>
                <li><a href="<%= profesors_path %>">Profesor</a></li>
                <li><a href="<%= alumnos_path %>">Alumno</a></li>
                <li><a href="<%= especialidads_path %>">Especialidad</a></li>
                <li><a href="<%= foros_path %>">Foros</a></li>
                <li><a href="<%= profesor_alumnos_path %>">Profesor - Alumnos</a></li>

              <% end %>
            </ul>



      <ul class="nav navbar-nav navbar-right">
        <% if usuario_signed_in? %>
        <li><a> <%= current_usuario.email %> </a></li>
        	<li><a href="<%= edit_usuario_registration_path(current_usuario) %>">Editar Perfil</a></li>
        	<li><a href="<%= destroy_usuario_session_path %>", data-method="delete">Cerrar Session</a></li>
        <% else %>
        	<li><a href="<%= new_usuario_session_path %>">Ingresar</a></li>
        	<li><a href="<%= new_usuario_registration_path %>">Registrarse</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>